[package]
name = "ISL-Veh-Reg-Hacking"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.28"
egui = "0.28"
reqwest = { version = "0.12", features = ["blocking"] }
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
